### ISSUE TITLE
Add support for non-Intel macOS

### ISSUE THREAD

**Issue by ilg-ul** [feross/arch#20]
Given the migration to Apple silicon, do not assume that if the platform is 'darwin', the architecture is 'x64'.

**Comment by feross** [comment]
What is the expected return value on Apple Silicon? I don't believe that Node.js's `os.arch()` has a return value for this yet. In any case, this can be solved as part of the effort to support more than `x32` and `x64` in https://github.com/feross/arch/issues/19
