### ISSUE TITLE
Doesn't work on 64-bit Linux with 32-bit Node executable

### ISSUE THREAD

**Issue by cb1kenobi** [feross/arch#3]
As you know, `process.arch` and `require('os').arch()` both return `ia32` from a 32-bit Node.js executable.

Assuming running 32-bit Node on 64-bit Linux, the `process.arch === 'x64'` test is false and proceeds to do WOW64 checks and those will fail on Linux resulting in incorrectly detecting a 64-bit Linux OS as `x86` instead of `x64`.

**Comment by feross** [comment]
Good point. The browser version of this module works correctly on all OSes, but the Node.js version only works on Mac and Windows at the moment. This should be easy to fix.

**Comment by cb1kenobi** [comment]
For the sake of getting my project done, I just ended up running `uname` on Linux. Not ideal, but at least it doesn't depend on a native Node.js C++ addon. Here's my code:

```javascript
// determine the operating system architecture
let arch = process.arch;
if (arch === 'ia32') {
	if ((process.platform === 'win32' && process.env.PROCESSOR_ARCHITEW6432) ||
		(process.platform === 'linux' && /x86_64/.test(execSync('uname -m')))) {
		// it's actually 64-bit
		arch = 'x64';
	} else {
		arch = 'x86';
	}
}
```

**Comment by feross** [comment]
Fixed by https://github.com/feross/arch/commit/2358996b6cac857ed48db3370e71279e39f5bf9c. Released as 2.1.0.

**Comment by cb1kenobi** [comment]
👍

**Comment by feross** [comment]
`uname -m` can return lots of possible values besides 'x86_64' for 64-bit, from my research. It'll probably work on most systems, but you might want to consider handling the other values, or using `getconf LONG_BIT` like I did here in `arch`. Cheers!

**Comment by cb1kenobi** [comment]
That's a good find! I know `uname -p` can return `i386` on OS X thanks to backwards compatibility, but it seemed `uname -m` was pretty solid. Neither here nor there, I like `getconf LONG_BIT` too! Thanks!
