### ISSUE TITLE
Not functioning properly on AppVeyor CI?

### ISSUE THREAD

**Issue by l3laze** [feross/arch#6]
This is the latest in a very long and very random line of "screw my project" problems I've been having while trying to build a cross-platform library with NodeJS. The library needs to find the proper Program Files folder based on the OS architecture (`Program Files` or `Program Files (x86)`) and apparently nothing I do is capable of properly detecting the architecture, including using your module.

At first I thought this was because AppVeyor was installing 32-bit NodeJS on either architecture, but even with that fixed using `Install-Product node $env:nodejs_version $env:Platform` to install the proper arch-specific versions it still fails exactly the same as every other time.

I have tried

* Using process/os module's .arch method.
* Using your module.
* Detecting the folders directly -- apparently don't exist/are inaccessible on AppVeyor by default.
* Detecting WoW64 folder directly  -- apparently don't exist/are inaccessible on AppVeyor by default.

My detection code is similar to the following:

    if (platform === 'win32') {
      if (arch === 'x86') {
        detected = path.join('C:', 'Program Files')
      } else {
        detected = path.join('C:', 'Program Files (x86)')
      }
    }

I have been changing the `arch === 'x86'` part around trying different things -- used 'ia32', 'x64', 'x86', 'ia64', and `||` combinations of ia32 & x86, but they all either fail completely or always return one value even on a machine of a different arch. Also, even with it testing for explicit values using `if/else if` instead of `if/else` it would still always return the value for one arch and ignore the other...lol.

My project is @ [https://github.com/l3laze/node-steam-config/tree/new](https://github.com/l3laze/node-steam-config/tree/new); working in the new branch as it's yet-another-rebuild and I've finally learned to stop doing that directly in a repo/it's dev branch.

I'm guessing this is just going to be something simple that I'm screwing up as usual, but after over 2 days now of trying to fix this I can't keep banging my head against this freaking wall.

**Comment by feross** [comment]
If you're using this module, you need to actually invoke `arch` since it's a function. So do `arch()` instead.

Other than that, I can't think of why this isn't working for you. It might help if you log out the value of `arch()` to see what it's set to on AppVeyor.
